-- 코드를 입력하세요
SELECT DATE_FORMAT(B.SALES_DATE, '%Y') YEAR, DATE_FORMAT(B.SALES_DATE, '%m') MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) USERS
FROM USER_INFO A
RIGHT JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3