# FISH_INFO, FISH_NAME_INFO(물고기 이름 테이블)
# FISH NAME이 BASS, SNAPPER인 물고기의 FISHTYPE을 FISHINFO 테이블과 조인한 다음 COUNT
-- 코드를 작성해주세요

SELECT COUNT(A.ID) AS FISH_COUNT FROM FISH_INFO A
LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME IN('BASS', 'SNAPPER')
